apiVersion: v1
kind: Service
metadata:
  labels:
    app: mealie
  name: mealie-svc
  namespace: mealie-ns
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
    nodePort: 30000
  selector:
    app: mealie
  type: NodePort
