apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"nginx-service","namespace":"default"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":8080}],"selector":{"app":"nginx"}}}
  creationTimestamp: "2025-12-12T23:54:32Z"
  name: nginx-service
  namespace: default
  resourceVersion: "165653"
  uid: 2c4a89fe-97b1-461c-b1da-ab5216257a9b
spec:
  clusterIP: 10.99.176.91
  clusterIPs:
  - 10.99.176.91
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
