apiVersion: v1
kind: Service
metadata:
  labels:
    app: mealie-app
  name: argocd-server
  namespace: argocd-server
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  - port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: mealie-app