apiVersion: v1
kind: Secret
metadata:
#  What deployment references secretKeyRef.name
  name: mongodb-secret
type: Opaque  #  base64
data:
# echo -n 'username' | base64
# echo -n 'password' | base64
#  referenced by deployment: ...env.name.valueFrom.secretKeyRef.key
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=