apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: <appName>
  namespace: <namespace>
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: <appName>
  namespace: <namespace>
subjects:
  - kind: ServiceAccount
    name: <appName>
    namespace: <namespace>
roleRef:
  kind: Role
  name: <appName>
  apiGroup: rbac.authorization.k8s.io
